### ISSUE TITLE
bvh run in ios is very slow

### ISSUE THREAD

**Issue by wbdsnx** [ZewanHuang/unitypackages#1]
My bvh file run in unity editor is very correct, however,run in ios slowly, the rate is around 0.5 time in ios

**Comment by huanngzh** [comment]
You can refer to [the section on optimizing performance on iOS in the official Unity documentation](https://docs.unity3d.com/Manual/iphone-performance.html) to make some modifications. Below I list some items that might help you:
- Don't use `try catch` statement
- Modify the configuration of Unity Editor in `Player Setting/OtherSetting`:
    - remove _Metal_ in _Graphics APIs_
    - set _Accelerometer Frequency_ into _Disabled_
    - set _Script Call Optimization_ into _Fast but no Exceptions_
