### ISSUE TITLE
第六步怎么设置

### ISSUE THREAD

**Issue by cssddnnc9527** [ZewanHuang/unitypackages#2]
感谢作者的贡献！！

请问第六步在哪里设置：

_脚本设置：filename 为 bvh 文件路径，TargetAvatar 指定角色，可直接拖拽设置_

非常感谢！！

**Comment by huanngzh** [comment]
你好，在提供的unitypackage中scenes里给出了SampleScene示例，点击场景中Human/unitychan对象，可以在Inspector面板中查看到设置示例。主要就是给avatar挂载BVHDriver.cs脚本，后在Inspector面板设置TargetAvatar和filename就可以。

![image](https://user-images.githubusercontent.com/78398294/189036083-64d28474-b274-4b80-b35e-3d7589f46e41.png)

**Comment by cssddnnc9527** [comment]
你好，谢谢回复，按照您的教程一步步设置后，出现了下面错误，请教一下，可能是什么原因，谢谢！
![Screenshot from 2022-09-08 15-27-57](https://user-images.githubusercontent.com/96765406/189061766-d4d1a2aa-7bea-40b4-8a7a-9766235a91c5.png)

**Comment by huanngzh** [comment]
下面的错误大概率是由于第一个_文件未找到_的异常引发的，建议 filename 的路径改为以 `Assets` 开头，例如 `Assets\BVHParser\Resources\bvh\13_29.bvh`。我注意到你填写的是 `/media/` 开头的路径，这样的路径会被 Unity 认为是从项目根目录开始的。

**Comment by cssddnnc9527** [comment]
提示Bonemaps.txt找不到

_Could not find file "/media/mashaoming/t21/code/Unity/3D_Project/Assets\BVHParser\Resources\Bonemaps.txt"_

可您提到的步骤里不需要设置这个文件的路径的，请问在哪里修改呢？再次感谢！

**Comment by huanngzh** [comment]
如果你成功引入了unitypackage，你可以在`Assets\BVHParser\Resources\Bonemaps.txt`找到这个文件，请确认BVHDriver面板中的Bonemap Path是否指向该文件路径。另外也可以检查一下你是否移动了该文件。

![image](https://user-images.githubusercontent.com/78398294/189101153-9be0f9b9-3d91-47d6-8d0e-2858d0d3a832.png)
