### ISSUE TITLE
导入该项目报错

### ISSUE THREAD

**Issue by XzavierDion** [ZewanHuang/unitypackages#3]
Assets/BVHParser/Scripts/BVHDriver.cs(57,19): error CS1061: 'BVHParser' does not contain a definition for 'getKeyFrame' and no accessible extension method 'getKeyFrame' accepting a first argument of type 'BVHParser' could be found (are you missing a using directive or an assembly reference?)

**Comment by ForeignSone** [comment]
public Dictionary<string,string> getHierachy()
{
    Dictionary<string, string> hierachy = new Dictionary<string, string>();
    foreach (BVHBone bb in boneList)
    {
        foreach (BVHBone bbc in bb.children)
        {
            hierachy.Add(bbc.name, bb.name);
        }
    }
    return hierachy;
}

private Quaternion eul2quat(float z, float y, float x)
{
    z = z * Mathf.Deg2Rad;
    y = y * Mathf.Deg2Rad;
    x = x * Mathf.Deg2Rad;

    // 动捕数据是ZYX，但是unity是ZXY
    float[] c = new float[3];
    float[] s = new float[3];
    c[0] = Mathf.Cos(x / 2.0f); c[1] = Mathf.Cos(y / 2.0f); c[2] = Mathf.Cos(z / 2.0f);
    s[0] = Mathf.Sin(x / 2.0f); s[1] = Mathf.Sin(y / 2.0f); s[2] = Mathf.Sin(z / 2.0f);

    return new Quaternion(
        c[0] * c[1] * s[2] - s[0] * s[1] * c[2],
        c[0] * s[1] * c[2] + s[0] * c[1] * s[2],
        s[0] * c[1] * c[2] - c[0] * s[1] * s[2],
        c[0] * c[1] * c[2] + s[0] * s[1] * s[2]
    );
}

public Dictionary<string,Quaternion> getKeyFrame(int frameIdx)
{
    Dictionary<string, string> hierachy = getHierachy();
    Dictionary<string, Quaternion> boneData = new Dictionary<string, Quaternion>();
    boneData.Add("pos", new Quaternion(
        boneList[0].channels[0].values[frameIdx],
        boneList[0].channels[1].values[frameIdx],
        boneList[0].channels[2].values[frameIdx],0));

    boneData.Add(boneList[0].name, eul2quat(
        boneList[0].channels[3].values[frameIdx],
        boneList[0].channels[4].values[frameIdx],
        boneList[0].channels[5].values[frameIdx]));
    foreach (BVHBone bb in boneList)
    {
        if (bb.name != boneList[0].name)
        {
            Quaternion localrot = eul2quat(bb.channels[3].values[frameIdx],
                                           bb.channels[4].values[frameIdx],
                                           bb.channels[5].values[frameIdx]);
            boneData.Add(bb.name, boneData[hierachy[bb.name]] * localrot);
        }                
    }            
    return boneData;
}

public Dictionary<string,Vector3> getOffset(float ratio) {
    Dictionary<string, Vector3> offset = new Dictionary<string, Vector3>();
    foreach(BVHBone bb in boneList)
    {
        offset.Add(bb.name, new Vector3(bb.offsetX * ratio, bb.offsetY * ratio, bb.offsetZ * ratio));
    }
    return offset;
}

**Comment by huanngzh** [comment]
如果正确导入unitypackage，正常是能检索到`getKeyFrame`等函数的，您可以检查一下版本或者导入的方式。
